### ISSUE TITLE
UndefinedFunctionError) function Poison.encode!/1 is undefined (module Poison is not available)

### ISSUE THREAD

**Issue by markquezada** [asakura/mixpanel_api_ex#18]
```
GenServer Mixpanel.Client terminating
2022-08-11T22:41:32.879434747Z ** (UndefinedFunctionError) function Poison.encode!/1 is undefined (module Poison is not available)
```

Seeing this in prod environments but not dev. The mix.lock file lists poison:

```
  "poison": {:hex, :poison, "3.1.0", "d9eb636610e096f86f25d9a46f35a9facac35609a7591b3be3326e99a0484665", [:mix], [], "hexpm", "fec8660eb7733ee4117b85f55799fd3833eb769a6df71ccf8903e8dc5447cfce"},
```

I'm using application inference and there's nothing explicitly set for `applications` in `mix.exs`. 

Any ideas?

**Comment by asakura** [comment]
I don't know for sure why this is happening but it seems bumping all dependencies to their modern versions solves the issue. @markquezada stay tuned, will release a new version of the package soon.
